openapi: 3.0.0

info:
  version: 0.0.1
  title: TFM Service
  description: The tfm service

servers:
  - url: http://localhost:8080/
    description: API location

tags:
  - name: "Objetos"
  - name: "Partidas"


paths:

  /objetos:

    post:
      summary: añadir objeto
      tags:
        - "Objetos"
      description: This is a description
      operationId: createObject
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectDTO'
      responses:
        "201":
          description: CREATED
    get:
      summary: Devuelve todos los objetos.
      tags:
        - "Objetos"
      description: This is a description
      operationId: getAllObjects
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
  /partidas:

    post:
      summary: añadir partida
      tags:
        - "Partidas"
      description: This is a description
      operationId: insertPartida
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartidaDTO'
      responses:
        "201":
          description: CREATED

components:

  schemas:

    ObjectDTO:
      description: This is the object model
      type: object
      required:
        - idObjeto
        - idVersion
        - nombre
      properties:
        idObjeto:
          description: id del objeto
          type: integer
        idVersion:
          description: version actual del objeto
          type: integer
        nombre:
          description: nombre del objeto
          type: string
    PartidaDTO:
      description: This is the partida model
      type: object
      required:
        - idPartida
        - gastos
        - informacion
      properties:
        idPartida:
          description: id de la partida
          type: integer
        gastos:
          description: gastos de la partida
          type: string
        informacion:
          description: informacion de la partida
          type: string
