openapi: 3.0.0

info:
  version: 0.0.1
  title: TFM Service
  description: The tfm service

servers:
  - url: http://localhost:8080/
    description: API location

tags:
  - name: "Objetos"
  - name: "Partidas"


paths:

  /objetos:

    post:
      summary: añadir objeto
      tags:
        - "Objetos"
      description: This is a description
      operationId: createObject
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectDTO'
      responses:
        "201":
          description: CREATED
    get:
      summary: Devuelve todos los objetos.
      tags:
        - "Objetos"
      description: This is a description
      operationId: getAllObjects
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
  /objetos/{objectId}:
    parameters:
      - name: objectId
        description: object id
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: Devuelve objeto por id objeto.
      tags:
        - "Objetos"
      description: This is a description
      operationId: getObjectById
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
  /objetos/version/{versionId}:
    parameters:
      - name: versionId
        description: version id
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: Devuelve objeto por id version.
      tags:
        - "Objetos"
      description: This is a description
      operationId: getObjectByVersionId
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
  /objetos/nuevaVersion:
    post:
      summary: nueva version de objeto
      tags:
        - "Objetos"
      description: This is a description
      operationId: createObjectVersion
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VersionDTO'
      responses:
        "201":
          description: CREATED
  /partidas:

    post:
      summary: añadir partida
      tags:
        - "Partidas"
      description: This is a description
      operationId: insertPartida
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartidaDTO'
      responses:
        "201":
          description: CREATED
  /partidas/importarPartidas:

    post:
      summary: añadir partidas
      tags:
        - "Partidas"
      description: This is a description
      operationId: importarPartidas
      requestBody:
        description: description
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: CREATED
        "200":
          description: OK
  /partidas/{partidaId}:
    parameters:
      - name: partidaId
        description: partida id
        schema:
          type: integer
        in: path
        required: true
      - name: user
        description: user
        schema:
          type: string
        in: query
        required: true
    get:
      summary: Devuelve partida por id de partida
      tags:
        - "Partidas"
      description: This is a description
      operationId: getPartidaById
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartidaResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
  /partidas/version/{versionId}:
    parameters:
      - name: versionId
        description: version id
        schema:
          type: integer
        in: path
        required: true
      - name: user
        description: user
        schema:
          type: string
        in: query
        required: true
    get:
      summary: Devuelve todas las partidas de una version.
      tags:
        - "Partidas"
      description: This is a description
      operationId: getPartidasByVersion
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartidaResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

  /usuario/registroPeticiones/{usuario}:
    parameters:
      - name: usuario
        description: user
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Devuelve el registro de peticiones de un usuario.
      tags:
        - "Usuarios"
      description: This is a description
      operationId: getRegistroPeticiones
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegistroPeticionesResponseDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

  /authentication:

    post:
      summary: autenticacion
      tags:
        - "Auth"
      description: This is a description
      operationId: authentication
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
      responses:
        "201":
          description: CREATED
components:

  schemas:
    ObjectDTO:
      description: This is the object model
      type: object
      required:
        - nombre
      properties:
        nombre:
          description: nombre del objeto
          type: string
    VersionDTO:
      description: This is the object model
      type: object
      required:
        - objectId
      properties:
        objectId:
          description: id del objeto
          type: integer
    ObjectResponseDTO:
      description: This is the object model
      type: object
      required:
        - nombre
        - idObjeto
        - idVersion
      properties:
        idObjeto:
          description: id del objeto
          type: integer
        idVersion:
          description: version del objeto
          type: integer
        nombre:
          description: nombre del objeto
          type: string
    PartidaDTO:
      description: This is the partida model
      type: object
      required:
        - idVersion
        - gastos
        - informacion
      properties:
        idVersion:
          description: id de la version
          type: integer
        gastos:
          description: gastos de la partida
          type: string
        informacion:
          description: informacion de la partida
          type: string
    PartidaResponseDTO:
      description: This is the partida response model
      type: object
      required:
        - idPartida
        - idVersion
        - gastos
        - informacion
      properties:
        idPartida:
          description: id de la partida
          type: integer
        idVersion:
          description: id de la version
          type: integer
        gastos:
          description: gastos de la partida
          type: string
        informacion:
          description: informacion de la partida
          type: string
    RegistroPeticionesResponseDTO:
      description: This is the registro peticiones response model
      type: object
      required:
        - idPeticion
        - tipoPeticion
        - idObjeto
        - idVersion
      properties:
        idPeticion:
          description: id de la peticion
          type: integer
        tipoPeticion:
          description: tipo de la peticion
          type: string
        idObjeto:
          description: id del objeto
          type: integer
        idVersion:
          description: id de la version
          type: integer
    AuthDTO:
      description: This is the object model
      type: object
      required:
        - usuario
      properties:
        usuario:
          description: usuario
          type: string

